# Generated by Django 4.1.7 on 2023-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPNO', models.IntegerField()),
                ('ENAME', models.CharField(max_length=100)),
                ('JOB', models.CharField(max_length=100)),
                ('MGR', models.IntegerField()),
                ('HIREDATE', models.DateField()),
                ('SAL', models.IntegerField()),
                ('COMM', models.IntegerField()),
                ('DEPTNO', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='dname',
            new_name='Dname',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='loc',
            new_name='Loc',
        ),
        migrations.AlterField(
            model_name='dept',
            name='DEPTNO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
