# Generated by Django 4.1.7 on 2023-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emp_rename_dname_dept_dname_rename_loc_dept_loc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMPNO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPNO', models.IntegerField()),
                ('ENAME', models.CharField(max_length=100)),
                ('JOB', models.CharField(max_length=100)),
                ('MGR', models.IntegerField()),
                ('HIREDATE', models.DateField()),
                ('SAL', models.IntegerField()),
                ('COMM', models.IntegerField()),
                ('DEPTNO', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='EMP',
        ),
    ]
